// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggwouvpwnwhdcsjyaiaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnd291dnB3bndoZGNzanlhaWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NzMyNjgsImV4cCI6MjA3MzM0OTI2OH0.NG2qW2CueFKBvyAlh-MC0O6LE297xvFaHrobLV8Hm1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'medic-all-app'
    }
  }
});